In [6]:
!pip install bitstring

000000000000


In [34]:
from bitstring import BitArray
import numpy as np

In [35]:
mem=np.zeros(shape=(12,4))
print(mem)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#Initialization of QTable
QTable={}

In [28]:
#Initialization of boardstate
#Initially all states->0
#0 means corresponding line is not drawnn
boardState=BitArray(uint=4095, length=12)
print(boardState.bin=='111111111111')
print(int('111111111111',2))

True
4095


In [36]:
player=["p1","p2"]
currentPlayer="p1"
box=[0,0,0,0]
currentState=BitArray(uint=0, length=12)
memoryForPlayer1=np.zeros(shape=(12,4))
memoryForPlayer2=np.zeros(shape=(12,4))
countForMemory1=0
countForMemory2=0
scoreForPlayer1=0
scoreForPlayer2=0

In [39]:
def isBoardFinished():
    return boardState.bin=='111111111111'

In [50]:
def transition(currentState,currentMove):
    temp=currentState.bin
    temp=temp[:currentMove-1]+'1'+temp[currentMove:]
    return temp
#print(transition(BitArray(uint=10,length=12),11))

000000001010


In [2]:
def numberOfNewBoxFormed(box,newState):
    count=0
    for i in range(4):
        if i==0 and box[i]==0:
            if newState[0]=='1' and newState[2]=='1' and newState[6]=='1' and newState[7]=='1':
                count+=1
                box[i]=1
        if i==1 and box[i]==0:
            if newState[1]=='1' and newState[3]=='1' and newState[7]=='1' and newState[8]=='1':
                count+=1
                box[i]=1
        if i==2 and box[i]==0:
            if newState[2]=='1' and newState[4]=='1' and newState[9]=='1' and newState[10]=='1':
                count+=1
                box[i]=1
        if i==3 and box[i]==0:
            if newState[3]=='1' and newState[5]=='1' and newState[10]=='1' and newState[11]=='1':
                count+=1
                box[i]=1
    return count
        
                

In [ ]:
def updateQTable()

In [26]:
while isBoardFinished==False:
    
    if(currentPlayer!="human"):
        currentMove=MakeMove(currentPlayer,currentState)
    else:
        currentMove=int(Input("Enter the line number:"))
    newState=transition(currentState,currentMove)    
    if currentPlayer=="p1":
        memoryForPlayer1[countForMemory1,0]=currentState.bin
        memoryForPlayer1[countForMemory1,1]=currentMove
        memoryForPlayer1[countForMemory1,2]=newState
        memoryForPlayer1[countForMemory1,3]=0
        countForMemory1+=1
        
    else:
        memoryForPlayer2[countForMemory2,0]=currentState.bin
        memoryForPlayer2[countForMemory2,1]=currentMove
        memoryForPlayer2[countForMemory2,2]=newState
        memoryForPlayer2[countForMemory2,3]=0
        countForMemory2+=1
        scoreForPlayer2+=numberOfNewBoxFormed(box,newState)*2
    numberOfBoxes=numberOfNewBoxFormed(box,newState)
    if numberOfBoxes>0:#Update this......:)
        if currentPlayer=="p1":
            scoreForPlayer1+=numberOfBoxes*2
        if currentPlayer=="p2":
            scoreForPlayer2+=numberOfBoxes*2
    else:
        if currentPlayer=="p1":
            currentPlayer="p2"
        else:
            currentPlayer="p1"
    boardState=BitArray(uint=int(newState,2),length=12)
    print(boardState)
    
        
    